const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Arr,
		C3.Plugins.Text,
		C3.Behaviors.Timer,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Arr.Acts.SplitString,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Arr.Exps.Back,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Browser.Acts.RequestFullScreen
	];
};
self.C3_JsPropNameTable = [
	{btn_kaynakca: 0},
	{btn_home: 0},
	{btn_bilgi: 0},
	{btn_emGecen: 0},
	{btn_ekranbuyut: 0},
	{btn_ekrankucult: 0},
	{btn_sesacik: 0},
	{btn_seskapali: 0},
	{Sine: 0},
	{btn_oyna: 0},
	{btn_tekraroyna: 0},
	{MoveTo: 0},
	{arkaplan1: 0},
	{araba_no: 0},
	{Tween: 0},
	{araba_kirmizi: 0},
	{araba_koyuyesil: 0},
	{Sprite3: 0},
	{araba_koyumavi: 0},
	{araba_açikmavi: 0},
	{araba_mor: 0},
	{araba_pembe: 0},
	{araba_sari: 0},
	{araba_turkuaz: 0},
	{araba_turuncu: 0},
	{araba_yesil: 0},
	{teker: 0},
	{kelime_gorsel: 0},
	{giris_arkaplan: 0},
	{giris_yazi: 0},
	{Touch: 0},
	{Mouse: 0},
	{Audio: 0},
	{Browser: 0},
	{infoarkplan: 0},
	{howtoplay: 0},
	{producedby: 0},
	{references: 0},
	{Sprite2: 0},
	{arkplancong: 0},
	{congrattulationsyazi: 0},
	{youhave: 0},
	{Sprite4: 0},
	{teker2: 0},
	{dogru_yanlis: 0},
	{correct_wrong: 0},
	{engel: 0},
	{meb_logo: 0},
	{sure_halka: 0},
	{arkaplan2: 0},
	{Array: 0},
	{Timer: 0},
	{sure: 0},
	{arabalar: 0},
	{butons: 0},
	{game: 0},
	{infopage: 0},
	{gorsel: 0},
	{dogru_sayisi: 0},
	{sure_deg: 0},
	{tiklama: 0}
];

self.InstanceType = {
	btn_kaynakca: class extends self.ISpriteInstance {},
	btn_home: class extends self.ISpriteInstance {},
	btn_bilgi: class extends self.ISpriteInstance {},
	btn_emGecen: class extends self.ISpriteInstance {},
	btn_ekranbuyut: class extends self.ISpriteInstance {},
	btn_ekrankucult: class extends self.ISpriteInstance {},
	btn_sesacik: class extends self.ISpriteInstance {},
	btn_seskapali: class extends self.ISpriteInstance {},
	btn_oyna: class extends self.ISpriteInstance {},
	btn_tekraroyna: class extends self.ISpriteInstance {},
	arkaplan1: class extends self.ISpriteInstance {},
	araba_kirmizi: class extends self.ISpriteInstance {},
	araba_koyuyesil: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	araba_koyumavi: class extends self.ISpriteInstance {},
	araba_açikmavi: class extends self.ISpriteInstance {},
	araba_mor: class extends self.ISpriteInstance {},
	araba_pembe: class extends self.ISpriteInstance {},
	araba_sari: class extends self.ISpriteInstance {},
	araba_turkuaz: class extends self.ISpriteInstance {},
	araba_turuncu: class extends self.ISpriteInstance {},
	araba_yesil: class extends self.ISpriteInstance {},
	teker: class extends self.ISpriteInstance {},
	kelime_gorsel: class extends self.ISpriteInstance {},
	giris_arkaplan: class extends self.ISpriteInstance {},
	giris_yazi: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	infoarkplan: class extends self.ISpriteInstance {},
	howtoplay: class extends self.ISpriteInstance {},
	producedby: class extends self.ISpriteInstance {},
	references: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	arkplancong: class extends self.ISpriteInstance {},
	congrattulationsyazi: class extends self.ISpriteInstance {},
	youhave: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	teker2: class extends self.ISpriteInstance {},
	dogru_yanlis: class extends self.ISpriteInstance {},
	correct_wrong: class extends self.ISpriteInstance {},
	engel: class extends self.ISpriteInstance {},
	meb_logo: class extends self.ISpriteInstance {},
	sure_halka: class extends self.ISpriteInstance {},
	arkaplan2: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	sure: class extends self.ITextInstance {},
	arabalar: class extends self.ISpriteInstance {},
	butons: class extends self.ISpriteInstance {},
	game: class extends self.ISpriteInstance {}
}